import { createElement as h } from "react";

function App() {
  return h(
    "div",
    null,
    h("h1", null, "This is SSG"),
    h("p", null, "This is a static site generated by React"),
  );
}
export default App;
